### ISSUE TITLE
Uncaught Error: Cannot find module 'player'

### ISSUE THREAD

**Issue by z3t0** [deathcap/voxel-plugins#4]
Cannot seem to load voxel-player. Any ideas?

**Comment by deathcap** [comment]
Are you calling it just 'player', or using the full name 'voxel-player'? 

I looked into using short names (dropping the voxel- prefix most/all voxel-plugin plugins have) but it caused some issues so for now the full NPM module name is always required

**Comment by z3t0** [comment]
Hmm. I think i found the problem, it was related to something else...

**Comment by z3t0** [comment]
Must have been a mistake on my end.
